rh._.exports({"0":["try / catch / finally","try / catch / finally"],"1":["try,catch,finally"],"2":["try,catch,finally"],"3":["\n  ","\n    ","\n    ","\n    ","\n      ","\n        ","try / catch / finally","\n      ","\n      ","\n        ","Click here to see this page in full context","\n      ","\n    ","\n  ","\n  ","\n\n\n\n  ","\n  ","\n  ","The ","try",", ","catch"," and ","finally"," statements can be used in your game for error checking and permit you to test out blocks of code and control what happens if any ","runtime exceptions","    occur. Using these will prevent the exception ending the game and showing the standard error message to the user, but this means that you will have to handle what happens next in that case, like saving out log files - for example - and ending the\n    game gracefully (note that if you choose to do nothing, your game may become unstable and not perform correctly).","\n  ","At it's most basic the ","try"," syntax is as follows:","\n  ","try","     {\n    ","     <statement1>;\n    ","     <statement2>;\n    ","     ...","     }\n  ","\n  ","However, having a ","try"," without anything to actually handle any exceptions the code may produce will not be very helpful, so we usually pair it with a ","catch",", with the following syntax:","\n  ","try","     {\n    ","     <statement1>;\n    ","     <statement2>;\n    ","     ...\n    ","     }\n    "," catch(<variable>)\n    ","     {\n    ","     <statement1>;\n    ","     <statement2>;\n    ","     ...\n    ","     }\n  ","\n  ","What ","catch"," does is permit you to run extra code supplied in the following block when an exception from the previous ","try"," has been caught. If this is a runtime exception, then the supplied variable can be used to access a ","struct","    which will contain the following information:","\n  ","{"," message : \"\",               // a string that is a short message for this exception"," longMessage : \"\",           // a string that is a longer message for this exception"," script : \"\",                // a string\n    that describes where the exception came from"," stacktrace : [ \"\", \"\" ],    // an array of strings that is the stack frame the exception was generated"," }\n  ","\n  ","A simple example of use is shown below:","\n  ","var a = 0, b = 0, c = 0;"," try\n    ","     {\n    ","     c = a div b;","     }\n    "," catch( _exception)","     {\n    ","     show_debug_message(_exception.message);\n    ","     show_debug_message(_exception.longMessage);\n    ","     show_debug_message(_exception.script);\n    ","     show_debug_message(_exception.stacktrace);\n    ","     }\n  ","\n  ","It may be that you want to run some code regardless of whether an exception was thrown or not, and so for that you can add in a ","finally"," block. The ","finally"," syntax is:","\n  ","finally","     {\n    ","     <statement1>;\n    ","     <statement2>;\n    ","     etc...\n    ","     }\n  ","\n  ","It is worth noting that you can have any combination of these together, ie:","\n  ","\n    ","try"," / ","finally","\n    ","try"," / ","catch","\n    ","try"," / ","catch"," / ","finally","\n  ","\n  ","Note that within the ","finally"," block you ","cannot ","use ","break",", ","continue",", ","exit"," or ","return"," statements as\n    they have no meaning in this context and the compiler will generate an error if they are used.","\n  ","Finally, you can also nest various ","try"," / ","catch"," / ","finally"," within each other, for example:","\n  ","var a = 0, b = 0, c = 0;"," try\n    ","     {\n    ","     try\n    ","         {\n    ","         c = a div b;","         }\n    ","     finally\n    ","         {\n    ","         ++a;\n    ","         }\n    ","     }\n    "," catch(_exception)\n    ","     {\n    ","     ++a;\n    ","     show_debug_message(_exception.message);\n    ","     show_debug_message(_exception.longMessage);\n    ","     show_debug_message(_exception.script);\n    ","     show_debug_message(_exception.stacktrace);\n    ","     }\n    "," finally\n    ","     {\n    ","     show_debug_message(\"a = \" + string(a));","     }\n  ","\n  ","It is worth noting that you can take over the default GML error message and use your own handler code by calling the function ","exception_unhandled_handler()",". This\n    ","runtime function"," permits you to supply a custom ","method"," to use that will be called whenever any unhandled exceptions occur in your game.","\n  "," ","\n  "," ","\n  "," ","\n  ","\n    ","\n      ","\n        ","Back: ","Language Features","\n        ","Next: ","throw","\n      ","\n    ","\n    ","\n  ","\n  ","\n  ","\n\n"],"4":["try / catch / finally"],"5":["© Copyright YoYo Games Ltd. 2020 All Rights Reserved"],"id":"185"})